# Generated by Django 5.0.4 on 2024-04-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='message',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
