# Generated by Django 5.0.4 on 2024-04-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0003_alter_email_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.CharField(default='  ', max_length=2000),
        ),
    ]
